# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  

- task: SonarCloudPrepare@3
  displayName: 'Configure SonarCloud'
  inputs:
        SonarCloud: 'azure2024'
        organization: 'murt30'
        #organization: 'spring-petclinic'
        scannerMode: 'Other'



#- task: JavaToolInstaller@0
#  inputs:
#    versionSpec: '17'
#    jdkArchitectureOption: 'x64'
#    jdkSourceOption: 'PreInstalled'
    


#- task: Maven@4

  #inputs:
      
      #mavenPomFile: 'pom.xml'
      #publishJUnitResults: true
     # testResultsFiles: '**/surefire-reports/TEST-*.xml'
      #javaHomeOption: 'JDKVersion'
     # mavenVersionOption: 'Default'
     # mavenPath: '/usr/share.apache-maven-4.246.1'
     #mavenAuthenticateFeed: false
     # effectivePomSkip: false      
     # sqMavenPluginVersionChoice: 'pom'
     # sonarQubeRunAnalysis: true
     # goals: 'spring-javaformat:apply package'
      
- task: Maven@3
  displayName: 'Execute Maven goal'
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-Dmaven.test.failure.ignore=true'
    mavenOptions: '-Xmx3072m'
    mavenVersionOption: 'Default'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
    codeCoverageToolOption: 'JaCoCo'
    testResultsFiles: '**/TEST-*.xml'
    goals: 'spring-javaformat:apply -Dcheckstyle.skip verify'
- task: SonarCloudAnalyze@3

  inputs:

            jdkversion: 'JAVA_HOME'
